ALTER TABLE `disc_ammo` 
ADD COLUMN `susturucu` INT NULL DEFAULT 0 
ADD COLUMN `fener` INT NULL DEFAULT 0
ADD COLUMN `tutamac` INT NULL DEFAULT 0
ADD COLUMN `kaplama` INT NULL DEFAULT 0
ADD COLUMN `durbun` INT NULL DEFAULT 0
ADD COLUMN `uzatilmis` INT NULL DEFAULT 0